<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

	<head>
		<!-- Meta -->
		<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
		<!-- End of Meta -->
		<!-- Page title -->
		<title>View Leave Details</title>		<!-- End of Page title -->
		<!-- Libraries -->
		<?php $url="http://localhost/lsm/public/admin";?>
		<link type="text/css" href="<?php echo $url;?>/css/layout.css" rel="stylesheet" />
		<script type="text/javascript" src="<?php echo $url; ?>/js/jquery-1.3.2.min.js"></script>
		<script type="text/javascript" src="<?php echo $url; ?>/js/easyTooltip.js"></script>
		<script type="text/javascript" src="<?php echo $url; ?>/js/jquery-ui-1.7.2.custom.min.js"></script>
		<script type="text/javascript" src="<?php echo $url; ?>/js/jquery.wysiwyg.js"></script>
		<script type="text/javascript" src="<?php echo $url; ?>/js/hoverIntent.js"></script>
		<script type="text/javascript" src="<?php echo $url; ?>/js/superfish.js"></script>
		<script type="text/javascript" src="<?php echo $url; ?>/js/custom.js"></script>
		

</head>
<body>


	<div id="main_menu"><div id="menu">
<ul id="nav" class="dropdown dropdown-horizontal">
				<li><a class="active-link" href="<?php echo $this->url(array('module'=>'admin','controller'=>'leave','action'=>'home'),null,true)?>">Admin</a></li>
				<li><a class="" href="<?php echo $this->url(array('module'=>'admin','controller'=>'leave','action'=>'viewemployee'),null,true)?>">Employee</a>
					<ul>
						<li><a class="" href="<?php echo $this->url(array('module'=>'admin','controller'=>'leave','action'=>'viewemp'))?>">View Employee</a></li>
						<li><a href="<?php echo $this->url(array('module'=>'admin','controller'=>'leave','action'=>'employee'),null,true)?>">Add Employee</a></li>
					</ul>
				</li>
                 <li><a class="" href="<?php echo $this->url(array('module'=>'admin','controller'=>'ld','action'=>'viewleave'),null,true)?>">Leave</a>
                 <ul>
						<li><a class="" href="<?php echo $this->url(array('module'=>'admin','controller'=>'ld','action'=>'viewleave'),null,true)?>">View Leave</a></li>					
					                 
                 </ul>
			    <li><a class="" href="<?php echo $this->url(array('module'=>'admin','controller'=>'adminsalary','action'=>'viewsalary'),null,true)?>">Salary</a>
					<ul>
						<li><a class="" href="<?php echo $this->url(array('module'=>'admin','controller'=>'adminsalary','action'=>'viewsalary'),null,true)?>">View Salary</a></li>
						<li><a class="" href="<?php echo $this->url(array('module'=>'admin','controller'=>'adminsalary','action'=>'createsalary'),null,true)?>">Create Salary</a></li>
					</ul>
				</li>
				        
               
			</ul></div></div>  
<div id="container">
		<!-- Header -->
		
  <div id="header">
				<!-- Top -->
    
				<!-- End of Top-->
<!-- The navigation bar -->


		<!-- End of Header -->
		<!-- Background wrapper -->
    	<div id="bgwrap">
     		<!-- Main Content -->
			<div id="content">
				<div id="main">				 
				  <div class="pad20">
<?php
foreach($this->resultviews as $resultRow)
				{		
				
				 $id=$resultRow['user_id'];
				 $name=$resultRow['name'];
				 $desg=$resultRow['designation'];
				 $fdate=$resultRow['fromdate'];
				 $tdate=$resultRow['todate'];
				 $res=$resultRow['reason'];
				 $dayCount=$resultRow['daycount'];
				 $status=$resultRow['status'];
				 
				 if($desg==0)
					$desg="Employee";
				else
					$desg="Manager";
				 if($status==0)
					$status="Pending";
				else if($status==1)
					$status="Accept";
				else 
					$status="Reject";
				
				 

				
?>
<form name="leaveRequest" action="<?php echo $this->url(array('module'=>'admin','controller'=>'ld','action'=>'handleleave')) ?>" method="post" onSubmit="return slectAction(this)">
<table>
<tr>
	<td><label>Chosse an Action:</label></td>
	<td><select name="leave">
		<option value="0">Pending</option>
		<option value="1">Accept</option>
		<option value="2">Reject</option>
		</select>
	</td>
	<td><input type="submit" value="Submit" class="button"></td>
</tr>
</table>
<br/>
<br/>
	
<table style="margin-bottom: 0pt; color:#fff; width:300px; background:#000; font:'Palatino Linotype', 'Book Antiqua', Palatino, serif; font-size:14px;" cellspacing="10px;"><tr align="center"><td><?php echo $name;?></td></tr></table>
<div>
<br  />
<table style="margin-bottom: 0pt; color:#fff; width:300px; background:#000; font:'Palatino Linotype', 'Book Antiqua', Palatino, serif; font-size:14px;" cellspacing="10px;">

      <tr><td colspan="3"><b><u>Leave Detail</u></b></td></tr>
      <tr><td>Name</td><td>:</td><td><?php echo $name;?></td></tr>
	  <tr><td>Designation</td><td>:</td><td><?php echo $desg;?></td></tr>
      <tr><td>From Date</td><td>:</td><td><?php echo $fdate; ?></td></tr>
      <tr><td>To Date</td><td>:</td><td><?php echo $tdate; ?></td></tr>
      <tr><td>Day Count</td><td>:</td><td><?php echo $dayCount; ?></td></tr>
      <tr><td>Reason</td><td>:</td><td><?php echo $res; ?></td></tr>
	  <tr><td>Status</td><td>:</td><td><?php echo $status; ?></td></tr>
</table>
<?php } ?>
	<a href="<?php echo $this->url(array('module'=>'admin','controller'=>'ld','action'=>'viewleave'),null,true)?>">Back</a>
</div>
</div></div></div></div></div></div>
</body>
</html>