<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

	<head>
		<!-- Meta -->
		<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
		<!-- End of Meta -->
		<!-- Page title -->
		<title>View Leave</title>		<!-- End of Page title -->
		<!-- Libraries -->
		<?php $url="http://localhost/lsm/public/admin";?>
		<link type="text/css" href="<?php echo $url;?>/css/layout.css" rel="stylesheet" />	
		<script type="text/javascript" src="js/jquery-1.3.2.min.js"></script>
		<script type="text/javascript" src="js/easyTooltip.js"></script>
		<script type="text/javascript" src="js/jquery-ui-1.7.2.custom.min.js"></script>
		<script type="text/javascript" src="js/jquery.wysiwyg.js"></script>
		<script type="text/javascript" src="js/hoverIntent.js"></script>
		<script type="text/javascript" src="js/superfish.js"></script>
		<script type="text/javascript" src="js/custom.js"></script>
		<!-- End of Libraries -->
        <script type="text/javascript">
    function confirmDelete()
    {
     return confirm("Are you sure you wish to delete this record?");
    }
   function confirmcancel()
   {
    return confirm("Are you sure you wish to cancel this booking?");
   }
   function checkForm(form)
   {
	  if(form.name.value == "") {
      alert("Error: Name cannot be blank!");
      form.name.focus();
      return false;
    }
   }
</script>	
	</head>
<body>
<div id="main_menu"><div id="menu">
<ul id="nav" class="dropdown dropdown-horizontal">
								<li><a class="active-link" href="<?php echo $this->url(array('module'=>'emp','controller'=>'leave','action'=>'home'),null,true)?>">Employee</a></li>
				<li><a class="" href="<?php echo $this->url(array('module'=>'emp','controller'=>'leave','action'=>'viewprofile'),null,true)?>">Profile</a>
					<ul>
						<li><a class="" href="<?php echo $this->url(array('module'=>'emp','controller'=>'leave','action'=>'viewprofile'),null,true)?>">View Profile</a></li>
						<li><a href="<?php echo $this->url(array('module'=>'emp','controller'=>'leave','action'=>'editprofile'),null,true)?>">Edit Profile</a></li>
					</ul>
				</li>
                  <li><a class="" href="<?php echo $this->url(array('module'=>'emp','controller'=>'ld','action'=>'viewleave'),null,true)?>">Leave</a>
                 <ul>
						<li><a class="" href="<?php echo $this->url(array('module'=>'emp','controller'=>'ld','action'=>'viewleave'),null,true)?>">View Leave</a></li>
						<li><a class="" href="<?php echo $this->url(array('module'=>'emp','controller'=>'ld','action'=>'applyleave'),null,true)?>">Apply Leave</a></li>					                 						
                 </ul>
				 <li><a class="" href="<?php echo $this->url(array('module'=>'emp','controller'=>'empsalary','action'=>'viewsalary'),null,true)?>">Salary</a>
					<ul>
						<li><a class="" href="<?php echo $this->url(array('module'=>'emp','controller'=>'empsalary','action'=>'viewsalary'),null,true)?>">View Salary</a></li>
					</ul> 
				</li>
               
			</ul></div></div>  
		
		<!-- Container -->
<div id="container">
		<!-- Header -->
		
  <div id="header">
				<!-- Top -->
    
				<!-- End of Top-->
<!-- The navigation bar -->


		<!-- End of Header -->
		<!-- Background wrapper -->
    	<div id="bgwrap">
     		<!-- Main Content -->
			<div id="content">
				<div id="main">				 
				  <div class="pad20">

                  <div id="tab">
				  <form action="<?php echo $this->url(array('module'=>'admin','controller'=>'ld','action'=>'searchleave'))?>" method="post" class="niceform" onSubmit='return checkForm(this)'>
                     <div><span style="font-size:15px;"></span><input type="text" name="name" title="Serch by Name"  />
                     <input class="button" type="submit" name="search" value="Search" /><br/><br />
                     </span></div>
                   </form>
          <table class="fullwidth" cellpadding="0" cellspacing="0" border="1">
										<thead>
                                        <tr><td colspan="2">&nbsp;<b>Leave Detail</b></font></td></tr>
										</thead>
                                        <thead>
                                        <tr>
                                        <td>Leave_Id</td>
                                        <td align="center">From Date</td>
                                        <td align="center">To Date</td>
										<td align="center">Days</td>
                                        <td align="center">Reason</td>
										<td align="center">Status</td></thead>                                        
										<tbody>
											<?php 

$i=1;

foreach($this->resultviews as $resultRow)
				{		
				
				 $id=$resultRow['leave_id'];
				 $res=$resultRow['reason'];
				 $fd=$resultRow['fromdate'];
				 $td=$resultRow['todate'];
				 $days=$resultRow['daycount'];
				 $status=$resultRow['status'];
				 if($status==0)
					$status="Pending";
				else if($status==1)
					$status="Accept";
				else 
					$status="Reject";
				
				 
				 
				
if($i%2 !== 0)
{
?>
<tr class="odd" height="40">
 <td width="75px" align="left"><?php echo $id; ?></td>
 <td width="150px" align="left"><?php echo $fd; ?></td>
  <td width="150px" align="left"><?php echo $td; ?></td>
 <td width="150px" align="left"><?php echo $days; ?></td>
 <td width="150px" align="left"><?php echo $res; ?></td>
 <td width="150px" align="left"><?php echo $status; ?></td>
 </tr>

<?php }
else { ?>
<tr class="colo1" height="40">
 <td width="75px" align="left"><?php echo $id; ?></td>
 <td width="150px" align="left"><?php echo $fd; ?></td>
  <td width="150px" align="left"><?php echo $td; ?></td>
 <td width="150px" align="left"><?php echo $days; ?></td>
 <td width="150px" align="left"><?php echo $res; ?></td>
 <td width="150px" align="left"><?php echo $status; ?></td>
 </tr>
<?php
}
$i++;
}

?>
</td>
</tr>
</tbody>
</table>
</div></div></div></div>
			
</body>
</html>