<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<?php $url="http://localhost/lsm/public/admin";?>
<link href="<?php echo $url;?>/css/main_style.css" rel="stylesheet" type="text/css" >
<link href="<?php echo $url;?>/css/styles.css" rel="stylesheet" type="text/css" >

</head>

<body>

<div id="header">
<div id="logo"><img src="<?php echo $url;?>/images/header_images/logo.jpg" /></div>
<div id="logout">Welcome <?php echo $this->name;?><b>|</b> <a href="<?php echo $this->url(array('controller'=>'index','action'=>'logout'))?>">Logout</a></div>
</div>


</body>
</html>
