<html>
<head>
	<?php $abs="http://localhost/lsm/public/admin"; ?>
	<link href="<?php echo $abs; ?>/css/main_style.css" rel="stylesheet" type="text/css" >
	<link href="<?php echo $abs; ?>/css/styles.css" rel="stylesheet" type="text/css" >
	<link href="<?php echo $abs; ?>/css/layout.css" rel="stylesheet" type="text/css" >
</head>
<body>
	<div id="footer">Copyright @ 2012 by Mind Zone.All Right Reserved.</div>
</body>
</html>