<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<!-- Mirrored from admin.myvirtualpaper.com/forgotpassword by HTTrack Website Copier/3.x [XR&CO'2010], Thu, 02 Feb 2012 21:13:05 GMT -->
<!-- Added by HTTrack --><meta http-equiv="content-type" content="text/html;charset=UTF-8"><!-- /Added by HTTrack -->
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<link rel="stylesheet" type="text/css" href="../login_css/login.css" />
<title>Mind Zone  Forgot Password</title>
</head>
<body>

<table width="100%" height="550" bgcolor="" cellpadding="0" cellspacing="0" style="position:relative;top:-25px;">
	<tr>
		<td>&nbsp;</td>
		<td width="198" bgcolor="" style="background-image:url(../login_images/login-left.jpg);background-repeat: no-repeat;background-position: bottom center">&nbsp;</td>
		<td width="285" valign="top">
			<div style="cursor:pointer;position:absolute;top:0px;background-color:;height:75px;width:285px;background-image:url(../login_images/login-bgtop-trans.png);background-repeat: no-repeat;background-position: top center"></div>
			<table width="100%" bgcolor="#ffffff" cellpadding="0" cellspacing="0">
				<tr height="147" bgcolor="">
					<td valign="bottom">
						<img style="cursor:pointer;" height="124" src="../login_images/login-logo.jpg" border="0" onclick='document.location.href="http://www.myvirtualpaper.com/"'>
					</td>
				</tr>
				<tr valign="top">
				<td>
				<span class="labels">Enter your username or email and click "Send New Password".</span>
				</td>
				</tr>
				<tr height="403" valign="top">
					<td style="background-image:url(../login_images/login-center.jpg);background-repeat:no-repeat;background-position: bottom center"><br><br>

						<form action="#" method="post">
							<table class="activity" style="background-color:;">
								<tr>
									<td class="labels">Username</td><td><input type="text" name="username" class="usertext" size="15" /></td>
								</tr>
								<tr>
									<td class="labels">OR Email</td><td><input type="text" name="email" class="usertext" size="15" /></td>
								</tr>
								<tr bgcolor=""><td colspan="2" style="height:8px;"></td></tr>
								<tr>
									<td width="80"><div style="font-size:10px;"><a href="<?php echo $this->url(array('controller'=>'index','action'=>'login'))?>" class="a">Back</a></div></td>
									<td align="right"><input class="cute_button_large" type="submit" style="position:relative;left:30px;font-size:10px; padding-top:2px;" value="Send new password"><!-- <input class="new_button" type="button" onclick="document.location='http://admin.myvirtualpaper.com/login'" style="" value="Back">--></td>
								</tr>
							</table>
						</form>
						<div id="me_box">
																					
						</div>
					
					</td>
				</tr>
		 	</table>
		</td>
		<td width="201" style="background-image:url(../login_images/login-right.jpg);background-repeat: no-repeat;background-position: bottom center">&nbsp;</td>
		<td>&nbsp;</td>
</table>


</body>

<!-- Mirrored from admin.myvirtualpaper.com/forgotpassword by HTTrack Website Copier/3.x [XR&CO'2010], Thu, 02 Feb 2012 21:13:05 GMT -->
<!-- Added by HTTrack --><meta http-equiv="content-type" content="text/html;charset=UTF-8"><!-- /Added by HTTrack -->
</html>