<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<!-- Mirrored from admin.myvirtualpaper.com/login by HTTrack Website Copier/3.x [XR&CO'2010], Thu, 02 Feb 2012 21:13:01 GMT -->
<!-- Added by HTTrack --><meta http-equiv="content-type" content="text/html;charset=UTF-8"><!-- /Added by HTTrack -->
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<title>Mind Zone HR Login</title>
<link href="../css/login.css" rel="stylesheet" type="text/css" />

<script type="text/javascript">
	function checkForm(form)
		{
			var email=document.getElementById('user');
			re= /^[\w\-\.\+]+\@[a-zA-Z0-9\.\-]+\.[a-zA-z0-9]{2,4}$/;
			if(!email.value.match(re))
			{
				alert("Please enter a valid User Address");
				email.focus();
				return false;
			}
			var pwd=document.getElementById('pass');
			if(form.pwd.value =="")
			{
				alert("Enter password");
				return false;
			}
		}
	</script> 

</head>
<body>

<table width="100%" height="550" bgcolor="" cellpadding="0" cellspacing="0" style="position:relative;top:-25px;">
	<tr>
		<td>&nbsp;</td>
		<td width="198" bgcolor="" style="background-image:url(../images/login_images/login-left.jpg);background-repeat: no-repeat;background-position: bottom center">&nbsp;</td>
		<td width="285" valign="top">
						<div style="cursor:pointer;position:absolute;top:0px;background-color:;height:75px;width:285px;background-image:url(../images/login_images/login-bgtop-trans.png);background-repeat: no-repeat;background-position: top center"></div>
						<table width="100%" bgcolor="#ffffff" cellpadding="0" cellspacing="0">
				<tr height="147" bgcolor="">
					<td valign="bottom">				<img style="cursor:pointer;" width="285" height="119" src="../images/login_images/login-logo.jpg" border="0">
					</td>
				</tr>
				<tr height="403" valign="top">
					<td style="background-image:url(../images/login_images/login-center.jpg);background-repeat:no-repeat;background-position: bottom center"><br><br>
						<div style="position:relative">
						<form action="<?php echo $this->url(array('controller'=>'index','action'=>'loginpost'))?>" method="post" onSubmit='' >
							<table class="activity" style="background-color:;">
								<tr>
									<td class="labels">Username</td><td width="169"><input type="text" name="user" id='user' class="usertext" size="15" value="" /></td>
							  </tr>
								<tr>
									<td class="labels">Password</td><td><input type="password" name="pass" id='pass' class="usertext" size="15" value="" /></td>
								</tr>
								<tr bgcolor=""><td colspan="2" style="height:8px;"></td></tr>
								<tr>
									<td width="93"><div style="font-size:10px;"><a href="<?php echo $this->url(array('controller'=>'index','action'=>'forgot'))?>" class="a">Forgot password</a></div></td>
					  <td align="right">
										<input class="login_button" type="submit" style="" value="" /> </td>
										<font color="red"><?php echo $this->fail;?>
								</tr>
							</table>
							<br><br><br>							<div style="color:#747474; font-size:12px;"><input type="checkbox" name="doRememberUsername"> Remember my username</div>
							<div style="color:#747474; font-size:12px;"><input type="checkbox" name="doRememberPassword"> Remember my password</div>
							<br>
							
							
						</form>
						
						<div id="me_box">
																				</div>
						</div>
					
					</td>
				</tr>
		 	</table>
		</td>
		<td width="201" style="background-image:url(../images/login_images/login-right.jpg);background-repeat: no-repeat;background-position: bottom center">&nbsp;</td>
		<td>&nbsp;</td>
</table>


</body>

<!-- Mirrored from admin.myvirtualpaper.com/login by HTTrack Website Copier/3.x [XR&CO'2010], Thu, 02 Feb 2012 21:13:03 GMT -->
<!-- Added by HTTrack --><meta http-equiv="content-type" content="text/html;charset=UTF-8"><!-- /Added by HTTrack -->
</html>
