<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

	<head>
		<!-- Meta -->
		<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
		<!-- End of Meta -->
		<!-- Page title -->
		<title>Edit Employee</title>		<!-- End of Page title -->
		<!-- Libraries -->
		<link type="text/css" href="../css/layout.css" rel="stylesheet" />
		<script type="text/javascript" src="js/jquery-1.3.2.min.js"></script>
		<script type="text/javascript" src="js/easyTooltip.js"></script>
		<script type="text/javascript" src="js/jquery-ui-1.7.2.custom.min.js"></script>
		<script type="text/javascript" src="js/jquery.wysiwyg.js"></script>
		<script type="text/javascript" src="js/hoverIntent.js"></script>
		<script type="text/javascript" src="js/superfish.js"></script>
		<script type="text/javascript" src="js/custom.js"></script>
</head>
<body>
<div id="container">
		<!-- Header -->
		
  <div id="header">
				<!-- Top -->
    
				<!-- End of Top-->
<!-- The navigation bar -->


		<!-- End of Header -->
		<!-- Background wrapper -->
    	<div id="bgwrap">
     		<!-- Main Content -->
			<div id="content">
				<div id="main">				 
				  <div class="pad20">
<?php
foreach($this->resultviews as $resultRow)
				{		
				
				 $id=$resultRow['user_id'];
				 $name=$resultRow['name'];
				 $bdate=$resultRow['birthdate'];
				 $phoneno=$resultRow['phoneno'];
				 $add=$resultRow['address'];
				 $qf=$resultRow['qualification'];
				 $jod=$resultRow['joiningdate'];
				 $end=$resultRow['endingdate'];
				 $gn=$resultRow['gender'];
				 $ms=$resultRow['maritalstatus'];
				 $desg=$resultRow['designation'];
				 $email=$resultRow['email'];
				 $pwd=$resultRow['password'];
				 $pan=$resultRow['pancardno'];
				 $status=$resultRow['status'];

				
?>
<body>		
					
<div id="container">

		

			<!-- Header -->

  <div id="header">

				

				<!-- Top -->

    

				<!-- End of Top-->

			

<!-- The navigation bar -->

			

		<!-- End of Header -->

			
						
		<!-- Background wrapper -->
					
		<div id="bgwrap">

		

			<!-- Main Content -->

			<div id="content">
						
                 <div id="main">				 
						
				  <div class="pad20">			
					
					
				  <form name="editEmp" action="<?php echo $this->url(array('controller'=>'leave','action'=>'updateemp'))?>" method="post" onSubmit='return checkForm(this)'>    

				  <fieldset>
					<legend>Employees Details</legend>           
						<table>
							<tr>
								<td><p><label>Name:</label></td>
								<td><input type="text" id="name" name="name"  value="<?php echo $name;?>" class=""  /></p></td>
								
								<td><p><label>Phone No:</label></td>
								<td><input type="text" name="phoneno"  id='phoneno' value="<?php echo $phoneno;?>" class=""  /></p></td>
									
								<td><p><label>E-Mail Id:</label></td>
								<td><input type="text" name="email"  id='email' value="<?php echo $email;?>" class=""  /></p></td>																	
							</tr>
							
							<tr>
								<td><p><label>Address:</label></td>
								<td><input type="text" id="" name="add"  value="<?php echo $add;?>" class=""  /></p></td>
								
								<td><p><label>Qualification:</label></td>
								<td><input type="text"  name="qf"  value="<?php echo $qf;?>" class=""  /></p></td>
								
								<td><p><label>Password:</label></td>
								<td><input type="password" id='pwd' name="pwd"  value="<?php echo $pwd;?>" class=""  /></p></td>																
							</tr>
							<tr>
							<td><p><label>Birthdate:</label></td>
								<td>
									<Select name="bday">
									<?php for($i=1;$i<=30;$i++) echo "<option value=$i>$i</option>";?>									
									</select>
									/
									<Select name="bmonth">
									<?php for($i=1;$i<=12;$i++) echo "<option value=$i>$i</option>";?>
									</select>
									/
									<select name="byear">
									<?php for($i=1980;$i<=2020;$i++) echo "<option value=$i>$i</option>";?>
									 </select>						
								</td>
								<td><label>Joining Date:</label></td>
								    <td>
									<Select name="jday">
									<?php for($i=1;$i<=30;$i++) echo "<option value=$i>$i</option>";?>									
									</select>
									/
									<Select name="jmonth">
									<?php for($i=1;$i<=12;$i++) echo "<option value=$i>$i</option>";?>
									</select>
									/
									<select name="jyear">
									<?php for($i=1980;$i<=2020;$i++) echo "<option value=$i>$i</option>";?>
									 </select>						
								</td>
								<td><label>Ending Date:</label></td>
								    <td>
									<Select name="eday">
									<?php for($i=1;$i<=30;$i++) echo "<option value=$i>$i</option>";?>									
									</select>
									/
									<Select name="emonth">
									<?php for($i=1;$i<=12;$i++) echo "<option value=$i>$i</option>";?>
									</select>
									/
									<select name="eyear">
									<?php for($i=1980;$i<=2020;$i++) echo "<option value=$i>$i</option>";?>
									 </select>						
								</td> 
								
							
							
							
								<td><p><label>Gender:</label></td>
								<td><select name="gender">
									<option value="0">Male</option>
									<option value="1">Female</option>
								</td>
								</tr>
								<tr>
									
									<td><p><label>Marital Staus:</label></td>
								<td><select name="ms">
									<option value="0">Yes</option>
									<option value="1">No</option>
								</td>
								
								<td><p><label>Designation:</label></td>
								<td><select name="desig">
									<option value="0">Employee</option>
									<option value="1">Manager</option>
								</td>
							
							
								<td><p><label>Status:</label></td>
								<td><select name="status">
									<option value="0">Active</option>
									<option value="1">Deactive</option>
								</td>
								<td><label>Pancard No:</label>
								<td><input type="text" name="pancard" value="<?php echo $pan;?>"></td>
								
							</tr>							
						<tr>
								<td><input type="submit" value="Submit" class="button" /></td>
								
						</tr>
						</table>
						
            </fieldset>
			
		
        <?php }?>
		  </div></div></div></div></div></div>

</body>
</html>