<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

	<head>
		<!-- Meta -->
		<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
		<!-- End of Meta -->
		<!-- Page title -->
		<title>View Employee</title>		<!-- End of Page title -->
		<!-- Libraries -->
		<?php $url="http://localhost/lsm/public/admin";?>
		<link type="text/css" href="<?php echo $url;?>/css/id/layout.css" rel="stylesheet" />
		<script type="text/javascript" src="<?php echo $url; ?>/js/jquery-1.3.2.min.js"></script>
		<script type="text/javascript" src="<?php echo $url; ?>/js/easyTooltip.js"></script>
		<script type="text/javascript" src="<?php echo $url; ?>/js/jquery-ui-1.7.2.custom.min.js"></script>
		<script type="text/javascript" src="<?php echo $url; ?>/js/jquery.wysiwyg.js"></script>
		<script type="text/javascript" src="<?php echo $url; ?>/js/hoverIntent.js"></script>
		<script type="text/javascript" src="<?php echo $url; ?>/js/superfish.js"></script>
		<script type="text/javascript" src="<?php echo $url; ?>/js/custom.js"></script>
		

</head>
<body>
<div id="container">
		<!-- Header -->
		
  <div id="header">
				<!-- Top -->
    
				<!-- End of Top-->
<!-- The navigation bar -->


		<!-- End of Header -->
		<!-- Background wrapper -->
    	<div id="bgwrap">
     		<!-- Main Content -->
			<div id="content">
				<div id="main">				 
				  <div class="pad20">
<?php
foreach($this->resultviews as $resultRow)
				{		
				
				 $id=$resultRow['user_id'];
				 $name=$resultRow['name'];
				 $bdate=$resultRow['birthdate'];
				 $phne=$resultRow['phoneno'];
				 $add=$resultRow['address'];
				 $qf=$resultRow['qualification'];
				 $jod=$resultRow['joiningdate'];
				 $end=$resultRow['endingdate'];
				 $gn=$resultRow['gender'];
				 $ms=$resultRow['maritalstatus'];
				 $desg=$resultRow['designation'];
				 $email=$resultRow['email'];
				 $pwd=$resultRow['password'];
				 $pan=$resultRow['pancardno'];
				 $status=$resultRow['status'];
				 
				 if($gn==0)
					$gn="Male";
				 else 
					$gn="Female";
				if($ms==0)
					$ms="Married";
				else
					$ms="Unmarried";
				if($desg==0)
					$desg="Employee";
				else
					$desg="Manager";
				if($status=0)
					$status="Active";
				else
					$status="Deactive";
				
				 

				
?>
<table>
<table>

      <tr><td colspan="3"><b><u>Employee Detail</u></b></td></tr>
      <tr><td>Name</td><td>:</td><td><?php echo $name;?></td></tr>
      <tr><td>Birthdate</td><td>:</td><td><?php echo $bdate; ?></td></tr>
      <tr><td>Phone No</td><td>:</td><td><?php echo $phne; ?></td></tr>
      <tr><td>Address</td><td>:</td><td><?php echo $add; ?></td></tr>
      <tr><td>Qualification</td><td>:</td><td><?php echo $qf; ?></td></tr>
	  <tr><td>Joining Date</td><td>:</td><td><?php echo $jod;?></td></tr>
      <tr><td>Ending Date</td><td>:</td><td><?php echo $end; ?></td></tr>
      <tr><td>Gender</td><td>:</td><td><?php echo $gn; ?></td></tr>
      <tr><td>Marital Status</td><td>:</td><td><?php echo $ms; ?></td></tr>
      <tr><td>Designation</td><td>:</td><td><?php echo $desg; ?></td></tr>
	  <tr><td>Email</td><td>:</td><td><?php echo $email; ?></td></tr>
      <tr><td>Password</td><td>:</td><td><?php echo $pwd; ?></td></tr>
      <tr><td>Status</td><td>:</td><td><?php echo $status; ?></td></tr>
     </table>
<?php } ?>
	<a href="<?php echo $this->url(array('module'=>'admin','controller'=>'leave','action'=>'viewemp'),null,true)?>">Back</a>
</div>
</div></div></div></div></div></div>
</body>
</html>