<html>
<head>
	<title>Mind Zone HR Admin</title>
	<?php $url="http://localhost/lsm/public/admin";?>
	<link rel="stylesheet" href="<?php echo $url;?>/css/core.css" type="text/css">
	<link rel="stylesheet" href="<?php echo $url;?>/css/skin_clean.css" type="text/css">
	<script type="text/javascript" src="js/easyTooltip.js"></script>
</head>
<body>

<div id="main_menu"><div id="menu">
<ul id="nav" class="dropdown dropdown-horizontal">
				<li><a class="active-link" href="<?php echo $this->url(array('module'=>'admin','controller'=>'leave','action'=>'home'),null,true)?>">Admin</a></li>
				<li><a class="" href="<?php echo $this->url(array('module'=>'admin','controller'=>'leave','action'=>'viewemp'),null,true)?>">Employee</a>
					<ul>
						<li><a class="" href="<?php echo $this->url(array('module'=>'admin','controller'=>'leave','action'=>'viewemp'))?>">View Employee</a></li>
						<li><a href="<?php echo $this->url(array('module'=>'admin','controller'=>'leave','action'=>'employee'),null,true)?>">Add Employee</a></li>
					</ul>
				</li>
                 <li><a class="" href="<?php echo $this->url(array('module'=>'admin','controller'=>'ld','action'=>'viewleave'),null,true)?>">Leave</a>
                 <ul>
						<li><a class="" href="<?php echo $this->url(array('module'=>'admin','controller'=>'ld','action'=>'viewleave'),null,true)?>">View Leave</a></li>					
					                 
                 </ul>
			    <li><a class="" href="<?php echo $this->url(array('module'=>'admin','controller'=>'adminsalary','action'=>'viewsalary'),null,true)?>">Salary</a>
					<ul>
						<li><a class="" href="<?php echo $this->url(array('module'=>'admin','controller'=>'adminsalary','action'=>'viewsalary'),null,true)?>">View Salary</a></li>
						<li><a class="" href="<?php echo $this->url(array('module'=>'admin','controller'=>'adminsalary','action'=>'createsalary'),null,true)?>">Create Salary</a></li>
					</ul>
				</li>
               
			</ul></div></div>  

		<div id="content">

			<div id="main">

				  <h1>Welcome, <span>Mind Zone Admin</span>!</h1>

				  <p>What would you like to do today?</p>

					

				  <div class="pad20">

					<!-- Big buttons -->

					  <ul class="dash">

						  <!--<li>

							  <a href="#" title="Write a new article" class="tooltip">

								  <img src="../images/assets_images/icons/8_48x48.png" alt="" />

								  <span>New article</span>

							  </a>

						  </li>

						  <li>

							  <a href="#" title="What your team posted" class="tooltip">

								  <img src="../images/assets_images/icons/7_48x48.png" alt="" />

								  <span>Last articles</span>

							  </a>

						  </li>-->

						  <li>

							  <a href="<?php echo $this->url(array('controller'=>'leave','action'=>'viewemp'))?>" title="View Employees" class="tooltip">

								  <img src="../images/assets_images/icons/16_48x48.png" alt="" />

								  <span>View Employees</span>

							  </a>

						  </li>

                           
                          

                           <li>

							  <a href="<?php echo $this->url(array('controller'=>'leave','action'=>'employee'))?>" title="Add Employees" class="tooltip">

								  <img src="../images/assets_images/icons/16_48x48.png" alt="" />

								  <span>Add Employees</span>

							  </a>

						  </li>


                          <li>

							 <a href="<?php echo $this->url(array('controller'=>'ld','action'=>'viewleave'))?>" title="View Leave Details" class="tooltip">

								  <img src="../images/assets_images/icons/21_48x48.png" alt="" />

								  <span>View Leave Details</span>

							  </a>

						  </li>


                          <li>

							  <a href="<?php echo $this->url(array('controller'=>'adminsalary','action'=>'viewsalary'))?>" title="View Salary Details" class="tooltip">

								  <img src="../images/assets_images/icons/21_48x48.png" alt="" />

								  <span>View Salary Details</span>

							  </a>

						  </li>
                          
                               <li>

							  <a href="<?php echo $this->url(array('controller'=>'adminsalary','action'=>'createsalary'))?>" title="Create Salary Slip" class="tooltip">

								  <img src="../images/assets_images/icons/21_48x48.png" alt="" />

								  <span>Create Salary Slip</span>

							  </a>

						  </li>

					  </ul>

					  <!-- End of Big buttons -->

				 

				

				

				

				    </div>	

						

			    </div>

		    </div>

			<!-- End of Main Content -->

				

			<!-- Sidebar -->

			

			<!-- End of Sidebar -->

				



		<!-- End of bgwrap -->
	</body>

</html>