<html>
<head>
	<title>Mind Zone Employee</title>
	<link rel="stylesheet" href="../css/core.css" type="text/css">
	<link rel="stylesheet" href="../css/skin_clean.css" type="text/css">
	<script type="text/javascript" src="js/easyTooltip.js"></script>
</head>
<body>
<div id="main_menu"><div id="menu">
<ul id="nav" class="dropdown dropdown-horizontal">
				<li><a class="active-link" href="<?php echo $this->url(array('module'=>'emp','controller'=>'leave','action'=>'home'),null,true)?>">Employee</a></li>
				<li><a class="" href="<?php echo $this->url(array('module'=>'emp','controller'=>'leave','action'=>'viewprofile'),null,true)?>">Profile</a>
					<ul>
						<li><a class="" href="<?php echo $this->url(array('module'=>'emp','controller'=>'leave','action'=>'viewprofile'),null,true)?>">View Profile</a></li>
						<li><a href="<?php echo $this->url(array('module'=>'emp','controller'=>'leave','action'=>'editprofile'),null,true)?>">Edit Profile</a></li>
					</ul>
				</li>
                 <li><a class="" href="<?php echo $this->url(array('module'=>'emp','controller'=>'ld','action'=>'viewleave'),null,true)?>">Leave</a>
                 <ul>
						<li><a class="" href="<?php echo $this->url(array('module'=>'emp','controller'=>'ld','action'=>'viewleave'),null,true)?>">View Leave</a></li>
						<li><a class="" href="<?php echo $this->url(array('module'=>'emp','controller'=>'ld','action'=>'applyleave'),null,true)?>">Apply Leave</a></li>					                 						
                 </ul>
				 <li><a class="" href="<?php echo $this->url(array('module'=>'emp','controller'=>'empsalary','action'=>'viewsalary'),null,true)?>">Salary</a>
					<ul>
						<li><a class="" href="<?php echo $this->url(array('module'=>'emp','controller'=>'empsalary','action'=>'viewsalary'),null,true)?>">View Salary</a></li>
					</ul> 
				</li>
               
			</ul></div></div>  
		
		<div id="content">

			<div id="main">

				  <h1>Welcome, <span>Mind Zone Employee</span>!</h1>

				  <p>What would you like to do today?</p>

					

				  <div class="pad20">

					<!-- Big buttons -->

					  <ul class="dash">

						  <!--<li>

							  <a href="#" title="Write a new article" class="tooltip">

								  <img src="../images/assets_images/icons/8_48x48.png" alt="" />

								  <span>New article</span>

							  </a>

						  </li>

						  <li>

							  <a href="#" title="What your team posted" class="tooltip">

								  <img src="../images/assets_images/icons/7_48x48.png" alt="" />

								  <span>Last articles</span>

							  </a>

						  </li>-->

						  <li>

							  <a href="<?php echo $this->url(array('controller'=>'leave','action'=>'viewprofile'))?>" title="Manage employees profile" class="tooltip">

								  <img src="../images/assets_images/icons/16_48x48.png" alt="" />

								  <span>View Profile</span>

							  </a>

						  </li>

                           
                          

                           <li>

							  <a href="<?php echo $this->url(array('controller'=>'leave','action'=>'editprofile'))?>" title="Edit Profile" class="tooltip">

								  <img src="../images/assets_images/icons/16_48x48.png" alt="" />
								  
								  <span>Edit Profile</span>


							  </a>

							  </a>

						  </li>


                          <li>

							  <a href="<?php echo $this->url(array('controller'=>'ld','action'=>'applyleave'))?>" title="Apply Leave" class="tooltip">

								  <img src="../images/assets_images/icons/21_48x48.png" alt="" />

								  <span>Apply Leave</span>

							  </a>

						  </li>
						  
						  
						   <li>

							  <a href="<?php echo $this->url(array('controller'=>'ld','action'=>'viewleave'))?>" title="View Leave" class="tooltip">

								  <img src="../images/assets_images/icons/21_48x48.png" alt="" />

								  <span>View Leave</span>

							  </a>

						  </li>

							<br/>
                          <li>

							  <a href="<?php echo $this->url(array('controller'=>'leave','action'=>'changepass'))?>" title="Change Your Password" class="tooltip">

								  <img src="../images/assets_images/icons/info_48.png" alt="" />

								  <span>Change Password</span>

							  </a>

						  </li>
                          
                          


						  <li>

							  <a href="<?php echo $this->url(array('controller'=>'empsalary','action'=>'viewsalary'))?>" title="View Cleints Details" class="tooltip">

								  <img src="../images/assets_images/icons/21_48x48.png" alt="" />

								  <span>View Salary Detail</span>

							  </a>

						  </li>
                          
                          


					
						 <!-- <li>

							  <a href="#" title="Lorem ipsum" class="tooltip">

								  <img src="../images/assets_images/icons/26_48x48.png" alt="" />

								  <span>Latest comments</span>

							  </a>

						  </li>-->

					  </ul>				  
					  <!-- End of Big buttons -->
				    </div>	
			    </div>
			</div>
			<!-- End of Main Content -->			

			<!-- Sidebar -->		

			<!-- End of Sidebar -->
			
		<!-- End of bgwrap -->
	</body>

</html>