<html>
<head>
	<title>Mind Zone HR Admin</title>
	<link rel="stylesheet" href="../css/core.css" type="text/css">
	<link rel="stylesheet" href="../css/skin_clean.css" type="text/css">
	<script type="text/javascript" src="js/easyTooltip.js"></script>
</head>
<body>

		<div id="content">

			<div id="main">

				  <h1>Welcome, <span>Mind Zone Admin</span>!</h1>

				  <p>What would you like to do today?</p>

					

				  <div class="pad20">

					<!-- Big buttons -->

					  <ul class="dash">

						  <!--<li>

							  <a href="#" title="Write a new article" class="tooltip">

								  <img src="../images/assets_images/icons/8_48x48.png" alt="" />

								  <span>New article</span>

							  </a>

						  </li>

						  <li>

							  <a href="#" title="What your team posted" class="tooltip">

								  <img src="../images/assets_images/icons/7_48x48.png" alt="" />

								  <span>Last articles</span>

							  </a>

						  </li>-->

						  <li>

							  <a href="<?php echo $this->url(array('controller'=>'leave','action'=>'employee'))?>" title="Manage employees and accounts" class="tooltip">

								  <img src="../images/assets_images/icons/16_48x48.png" alt="" />

								  <span>Employees Details</span>

							  </a>

						  </li>

                           
                          

                           <li>

							  <a href="email_setting.php" title="Update Email Setting" class="tooltip">

								  <img src="../images/assets_images/icons/25_48x48.png" alt="" />

								  <span>Email Setting</span>

							  </a>

						  </li>


                          <li>

							  <a href="terms_condition.php" title="Add Terms And Conditions" class="tooltip">

								  <img src="../images/assets_images/icons/19_48x48.png" alt="" />

								  <span>Terms And Conditions</span>

							  </a>

						  </li>


                          <li>

							  <a href="admin_chpass.php" title="Change Your Password" class="tooltip">

								  <img src="../images/assets_images/icons/info_48.png" alt="" />

								  <span>Change Password</span>

							  </a>

						  </li>
                          
                          <li>

							  <a href="admin_change_title.php" title="Change Admin Page Title" class="tooltip">

								  <img  height="50" width="70" src="../images/assets_images/icons/change.png" alt="" />

								  <span>Change Page Title</span>

							  </a>

						  </li><br />


						  <li>

							  <a href="view_client_detail.php" title="View Cleints Details" class="tooltip">

								  <img src="../images/assets_images/icons/21_48x48.png" alt="" />

								  <span>View Clients Detail</span>

							  </a>

						  </li>
                          
                          <li>

							  <a href="view_blog_detail.php" title="View Leave Details" class="tooltip">

								  <img src="../images/assets_images/icons/21_48x48.png" alt="" />

								  <span>View Leave Details</span>

							  </a>

						  </li>
                          
                          <li>

							  <a href="view_info_detail.php" title="View Information Details" class="tooltip">

								  <img src="../images/assets_images/icons/21_48x48.png" alt="" />

								  <span>View Info Detail</span>

							  </a>

						  </li>


						  <li>

							  <a href="view_service_detail.php" title="View Service Details" class="tooltip">

								  <img src="../images/assets_images/icons/21_48x48.png" alt="" />

								  <span>View Services Details</span>

							  </a>

						  </li>
                          
                           <li>

							  <a href="view_cat_detail.php" title="View Category Details" class="tooltip">

								  <img src="../images/assets_images/icons/21_48x48.png" alt="" />

								  <span>View Category Details</span>

							  </a>

						  </li>


					
						 <!-- <li>

							  <a href="#" title="Lorem ipsum" class="tooltip">

								  <img src="../images/assets_images/icons/26_48x48.png" alt="" />

								  <span>Latest comments</span>

							  </a>

						  </li>-->

					  </ul>

					  <!-- End of Big buttons -->

				 

				

				

				

				    </div>	

						

			    </div>

		    </div>

			<!-- End of Main Content -->

				

			<!-- Sidebar -->

			

			<!-- End of Sidebar -->

				



		<!-- End of bgwrap -->
	</body>

</html>